// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrf-CZIKnpk5SEXFal5URbU8EpBZOc3qQ',
    appId: '1:348255973061:web:c2ae8281ea2830a5618aac',
    messagingSenderId: '348255973061',
    projectId: 'ecommerceapp-e96e4',
    authDomain: 'ecommerceapp-e96e4.firebaseapp.com',
    storageBucket: 'ecommerceapp-e96e4.appspot.com',
    measurementId: 'G-4CT6FE9SSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvopgjPSEa9nivK6J8AzLmFtLqnNZj45g',
    appId: '1:348255973061:android:aad550aec7cbaa7b618aac',
    messagingSenderId: '348255973061',
    projectId: 'ecommerceapp-e96e4',
    storageBucket: 'ecommerceapp-e96e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD7mbnuXOV8Lb3YvLLBU5jXWeF-jPymNE',
    appId: '1:348255973061:ios:515d5ddcdc3f251f618aac',
    messagingSenderId: '348255973061',
    projectId: 'ecommerceapp-e96e4',
    storageBucket: 'ecommerceapp-e96e4.appspot.com',
    androidClientId: '348255973061-bpthrtdnmapkp4rf75t198p3qsp0vjc6.apps.googleusercontent.com',
    iosClientId: '348255973061-o757skf1hugqo4fveegj5esn6ueg8ak9.apps.googleusercontent.com',
    iosBundleId: 'com.alinawab.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrf-CZIKnpk5SEXFal5URbU8EpBZOc3qQ',
    appId: '1:348255973061:web:a3593afdf4465af1618aac',
    messagingSenderId: '348255973061',
    projectId: 'ecommerceapp-e96e4',
    authDomain: 'ecommerceapp-e96e4.firebaseapp.com',
    storageBucket: 'ecommerceapp-e96e4.appspot.com',
    measurementId: 'G-BEJ5Z190FS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD7mbnuXOV8Lb3YvLLBU5jXWeF-jPymNE',
    appId: '1:348255973061:ios:e7182d0de9e48b9c618aac',
    messagingSenderId: '348255973061',
    projectId: 'ecommerceapp-e96e4',
    storageBucket: 'ecommerceapp-e96e4.appspot.com',
    androidClientId: '348255973061-bpthrtdnmapkp4rf75t198p3qsp0vjc6.apps.googleusercontent.com',
    iosClientId: '348255973061-uoqb3s65824f256e4ltotpuqi0lf101j.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

}